### ISSUE TITLE
Additional well known error tracking issue

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-exec#39]
Possible candidates, split out to new issue if addressing any of these:

- [ ] config syntax
- [ ] provider side errors
- [x] TF CLI version constraint error
  - https://github.com/hashicorp/terraform-exec/pull/66
- [ ] state file version mismatch error (other state errors? ie connectivity?)
- [ ] provider panic
- [ ] Provider installation error

**Comment by paultyng** [comment]
Going to close this in favor of more specific requests.
